/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_MPU9250_Master.h"
#include "I2C_MPU9250_Master_PVT.h"
#include "MPU9250_ISR.h"
#include "MPU9250_INT_aliases.h"
#include "MPU9250_INT.h"
#include "UART_Debug.h"
#include "UART_BT.h"
#include "PIN_BUTTON_aliases.h"
#include "PIN_BUTTON.h"
#include "PIN_LED_aliases.h"
#include "PIN_LED.h"
#include "UART_Debug_IntClock.h"
#include "UART_BT_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

